import React from 'react'

const AlphabetsCard = () => {
  return (
    <div className='uni-alphabets px-[16px] scrollbar-hidden overflow-x-auto whitespace-nowrap snap-x snap-mandatory scroll-px-[24px] md:px-[24px] xl2:px-[0]'>
          <ul className='w-fit flex flex-row gap-[6px] mt-[12px] mb-[20px]'>
            <li className='w-[28px] h-[28px] flex'><a href="#" className="w-full flex items-center justify-center font-regular para text-secondary-500 hover:bg-secondary-500 hover:text-white active:bg-secondary-500 active:text-white rounded-[24px] px-[9px] py-[2px] select-none">A</a></li>
            <li className='w-[28px] h-[28px] flex'><a href="#" className="w-full flex items-center justify-center font-regular para text-secondary-500 hover:bg-secondary-500 hover:text-white active:bg-secondary-500 active:text-white rounded-[24px] px-[9px] py-[2px] select-none">B</a></li>
            <li className='w-[28px] h-[28px] flex'><a href="#" className="w-full flex items-center justify-center font-regular para text-secondary-500 hover:bg-secondary-500 hover:text-white active:bg-secondary-500 active:text-white rounded-[24px] px-[9px] py-[2px] select-none">C</a></li>
            <li className='w-[28px] h-[28px] flex'><a href="#" className="w-full flex items-center justify-center font-regular para text-secondary-500 hover:bg-secondary-500 hover:text-white active:bg-secondary-500 active:text-white rounded-[24px] px-[9px] py-[2px] select-none">D</a></li>
            <li className='w-[28px] h-[28px] flex'><a href="#" className="w-full flex items-center justify-center font-regular para text-secondary-500 hover:bg-secondary-500 hover:text-white active:bg-secondary-500 active:text-white rounded-[24px] px-[9px] py-[2px] select-none">E</a></li>
            <li className='w-[28px] h-[28px] flex'><a href="#" className="w-full flex items-center justify-center font-regular para text-secondary-500 hover:bg-secondary-500 hover:text-white active:bg-secondary-500 active:text-white rounded-[24px] px-[9px] py-[2px] select-none">F</a></li>
            <li className='w-[28px] h-[28px] flex'><a href="#" className="w-full flex items-center justify-center font-regular para text-secondary-500 hover:bg-secondary-500 hover:text-white active:bg-secondary-500 active:text-white rounded-[24px] px-[9px] py-[2px] select-none">G</a></li>
            <li className='w-[28px] h-[28px] flex'><a href="#" className="w-full flex items-center justify-center font-regular para text-secondary-500 hover:bg-secondary-500 hover:text-white active:bg-secondary-500 active:text-white rounded-[24px] px-[9px] py-[2px] select-none">H</a></li>
            <li className='w-[28px] h-[28px] flex'><a href="#" className="w-full flex items-center justify-center font-regular para text-secondary-500 hover:bg-secondary-500 hover:text-white active:bg-secondary-500 active:text-white rounded-[24px] px-[9px] py-[2px] select-none">I</a></li>
            <li className='w-[28px] h-[28px] flex'><a href="#" className="w-full flex items-center justify-center font-regular para text-secondary-500 hover:bg-secondary-500 hover:text-white active:bg-secondary-500 active:text-white rounded-[24px] px-[9px] py-[2px] select-none">J</a></li>
            <li className='w-[28px] h-[28px] flex'><a href="#" className="w-full flex items-center justify-center font-regular para text-secondary-500 hover:bg-secondary-500 hover:text-white active:bg-secondary-500 active:text-white rounded-[24px] px-[9px] py-[2px] select-none">K</a></li>
            <li className='w-[28px] h-[28px] flex'><a href="#" className="w-full flex items-center justify-center font-regular para text-secondary-500 hover:bg-secondary-500 hover:text-white active:bg-secondary-500 active:text-white rounded-[24px] px-[9px] py-[2px] select-none">L</a></li>
            <li className='w-[28px] h-[28px] flex'><a href="#" className="w-full flex items-center justify-center font-regular para text-secondary-500 hover:bg-secondary-500 hover:text-white active:bg-secondary-500 active:text-white rounded-[24px] px-[9px] py-[2px] select-none">M</a></li>
            <li className='w-[28px] h-[28px] flex'><a href="#" className="w-full flex items-center justify-center font-regular para text-secondary-500 hover:bg-secondary-500 hover:text-white active:bg-secondary-500 active:text-white rounded-[24px] px-[9px] py-[2px] select-none">N</a></li>
            <li className='w-[28px] h-[28px] flex'><a href="#" className="w-full flex items-center justify-center font-regular para text-secondary-500 hover:bg-secondary-500 hover:text-white active:bg-secondary-500 active:text-white rounded-[24px] px-[9px] py-[2px] select-none">O</a></li>
            <li className='w-[28px] h-[28px] flex'><a href="#" className="w-full flex items-center justify-center font-regular para text-secondary-500 hover:bg-secondary-500 hover:text-white active:bg-secondary-500 active:text-white rounded-[24px] px-[9px] py-[2px] select-none">P</a></li>
            <li className='w-[28px] h-[28px] flex'><a href="#" className="w-full flex items-center justify-center font-regular para text-secondary-500 hover:bg-secondary-500 hover:text-white active:bg-secondary-500 active:text-white rounded-[24px] px-[9px] py-[2px] select-none">Q</a></li>
            <li className='w-[28px] h-[28px] flex'><a href="#" className="w-full flex items-center justify-center font-regular para text-secondary-500 hover:bg-secondary-500 hover:text-white active:bg-secondary-500 active:text-white rounded-[24px] px-[9px] py-[2px] select-none">R</a></li>
            <li className='w-[28px] h-[28px] flex'><a href="#" className="w-full flex items-center justify-center font-regular para text-secondary-500 hover:bg-secondary-500 hover:text-white active:bg-secondary-500 active:text-white rounded-[24px] px-[9px] py-[2px] select-none">S</a></li>
            <li className='w-[28px] h-[28px] flex'><a href="#" className="w-full flex items-center justify-center font-regular para text-secondary-500 hover:bg-secondary-500 hover:text-white active:bg-secondary-500 active:text-white rounded-[24px] px-[9px] py-[2px] select-none">T</a></li>
            <li className='w-[28px] h-[28px] flex'><a href="#" className="w-full flex items-center justify-center font-regular para text-secondary-500 hover:bg-secondary-500 hover:text-white active:bg-secondary-500 active:text-white rounded-[24px] px-[9px] py-[2px] select-none">U</a></li>
            <li className='w-[28px] h-[28px] flex'><a href="#" className="w-full flex items-center justify-center font-regular para text-secondary-500 hover:bg-secondary-500 hover:text-white active:bg-secondary-500 active:text-white rounded-[24px] px-[9px] py-[2px] select-none">V</a></li>
            <li className='w-[28px] h-[28px] flex'><a href="#" className="w-full flex items-center justify-center font-regular para text-secondary-500 hover:bg-secondary-500 hover:text-white active:bg-secondary-500 active:text-white rounded-[24px] px-[9px] py-[2px] select-none">W</a></li>
            <li className='w-[28px] h-[28px] flex'><a href="#" className="w-full flex items-center justify-center font-regular para text-secondary-500 hover:bg-secondary-500 hover:text-white active:bg-secondary-500 active:text-white rounded-[24px] px-[9px] py-[2px] select-none">X</a></li>
            <li className='w-[28px] h-[28px] flex'><a href="#" className="w-full flex items-center justify-center font-regular para text-secondary-500 hover:bg-secondary-500 hover:text-white active:bg-secondary-500 active:text-white rounded-[24px] px-[9px] py-[2px] select-none">Y</a></li>
            <li className='w-[28px] h-[28px] flex'><a href="#" className="w-full flex items-center justify-center font-regular para text-secondary-500 hover:bg-secondary-500 hover:text-white active:bg-secondary-500 active:text-white rounded-[24px] px-[9px] py-[2px] select-none">Z</a></li>
          </ul>
        </div>
  )
}

export default AlphabetsCard